name: register_broadcast_receiver
description: Flutter register broadcast receiver plugin.
version: 0.0.2
homepage: https://github.com/ag1le0/register_broadcast_receiver

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.hz.wu.register_broadcast_receiver.register_broadcast_receiver
        pluginClass: BroadcastReceiverPlugin
